title: Demoni ry
longtitle: Metropolian kulttuurialan opiskelijayhdistys Demoni ry
description: >
  Demoni ry on Metropolia Ammattikorkeakoulun
  kulttuurin opiskelijoiden opiskelijayhdistys.
lang: fi

# Build settings
permalink: /:title/
markdown: kramdown
url: https://beta.demoniry.fi
