title: Demoni ry
longtitle: Metropolian kulttuurialan opiskelijayhdistys Demoni ry
description: >
  Demoni on Metropolia ammattikorkeakoulun kulttuurialan opiskelijayhdistys,
  joka toimii Helsingin Arabiassa ja Vantaan Tikkurilassa.
lang: fi

# Build settings
permalink: /:title/
source: _content
markdown: kramdown

# Editor settings
prose:
  rooturl: _sisalto
  siteurl: "https://akselinurmio.github.io/demoni/"
