title: Demoni ry
longtitle: Metropolian kulttuurialan opiskelijayhdistys Demoni ry
description: >
  Demoni ry on Metropolia Ammattikorkeakoulun kulttuurin opiskelijoiden
  opiskelijayhdistys, joka järjestää monenlaista vapaa-ajan toimintaa
  opiskelun oheen, hoitaa jäsentensä edunvalvontaa ja myy opiskelijaelämään
  kuuluvia tuotteita. Demoni toimii aktiivisesti yhteistyössä Metropolia
  Ammattikorkeakoulun opiskelijakunta METKAn kanssa.
lang: fi

# Build settings
permalink: /:title/
markdown: kramdown
